channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - tbb ==2020.2
  - bowtie2 ==2.4.1  # Keep consistent with version specified in bowtie2/align
  - samtools ==1.10

#current problems with update to tbb (2021.1.1, conda-forge) breaks bowtie2 (bioconda)
#therefore we force tbb to this version
