channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - tbb
  - bowtie2
  - samtools
#  - tbb ==2020.2
#  - bowtie2 ==2.4.1  # Keep consistent with version specified in bowtie2/align
#  - samtools

#current problems with update to tbb (2021.1.1, conda-forge) breaks bowtie2 (bioconda)
#therefore we force tbb to this version
